name: 2-2-Create Network-Terraform Plan Manual
on: [workflow_dispatch]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}
  AWS_SSH_PUBLIC_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PUBLIC_KEY }}

jobs:
  terraform_plan:
    name: Terraform Plan Manual
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform plan
      run: |
        cd ./2-create-network
        terraform init
        terraform validate
        terraform plan