name: 4a-1 | Create | EC2 Setup
on: 
  workflow_dispatch
env:
  REGION: ${{ vars.REGIAO }}
  REMOTE_STATE_BUCKET: ${{ vars.REMOTE_STATE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}

jobs:
  main_job:
    name: "Create: EC2 Setup"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PRIVATE_KEY }}
        
    - name: "EC2 Setup: Setup backend, run terraform init and apply."
      env:
        KEY_TF_STATE: "EC2 Setup/terraform.tfstate"
        LOCAL_FOLDER: "4a-EC2 Setup"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        terraform init -backend-config=./backend.tfvars
        terraform state list
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}" \
          -var "domain-base=${{vars.DOMAIN_BASE}}" \
          -var "rds-1-db-name=${{vars.RDS_1_DB_NAME}}" \
          -var "rds-1-db-username=${{vars.RDS_1_DB_USERNAME}}" \
          -var "rds-1-db-password=${{secrets.RDS_1_DB_PASSWORD}}" \
          -var "magento-public-key=${{secrets.MAGENTO_PUBLIC_KEY}}" \
          -var "magento-private-key=${{secrets.MAGENTO_PRIVATE_KEY}}" \
          -var "magento-admin-email=${{vars.MAGENTO_ADMIN_EMAIL}}" \
          -var "magento-admin-firstname=${{vars.MAGENTO_ADMIN_FIRSTNAME}}" \
          -var "magento-admin-lastname=${{vars.MAGENTO_ADMIN_LASTNAME}}" \
          -var "magento-admin-user=${{vars.MAGENTO_ADMIN_USER}}" \
          -var "magento-admin-password=${{secrets.MAGENTO_ADMIN_PASSWORD}}"
