name: 6-1 | Create | ELB
on: 
  workflow_dispatch
env:
  REGION: ${{ vars.REGIAO }}
  REMOTE_STATE_BUCKET: ${{ vars.REMOTE_STATE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}  

jobs:
  main_job:
    name: "Create: ELB"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    - name: "ELB: Setup backend, run terraform init and apply."
      env:
        KEY_TF_STATE: "ELB/terraform.tfstate"
        LOCAL_FOLDER: "6-ELB"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        terraform init -backend-config=./backend.tfvars
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}" \
          -var "domain-base=${{vars.DOMAIN_BASE}}"